
import { Freelancer, Job } from "@/types/freelance";

// Mock data for freelancers
export const mockFreelancers: Freelancer[] = [
  {
    id: "1",
    name: "Alex Johnson",
    title: "Blockchain Developer",
    hourlyRate: 85,
    rating: 4.9,
    completedJobs: 47,
    bio: "Experienced blockchain developer with 5+ years of experience in DeFi projects and smart contracts.",
    skills: ["Solidity", "Ethereum", "Smart Contracts", "DeFi", "Web3.js"],
    acceptedCryptocurrencies: ["BTC", "ETH", "USDT"],
    availability: "Full-time",
    location: "Remote",
    category: "development",
    avatar: "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
  },
  {
    id: "2",
    name: "Sarah Williams",
    title: "UI/UX Designer",
    hourlyRate: 65,
    rating: 4.8,
    completedJobs: 31,
    bio: "Creative UI/UX designer specialized in crypto and blockchain applications with a minimalist approach.",
    skills: ["UI Design", "UX Research", "Figma", "Webflow", "Branding"],
    acceptedCryptocurrencies: ["BTC", "ETH", "SOL"],
    availability: "Part-time",
    location: "Remote",
    category: "design",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
  },
  {
    id: "3",
    name: "Michael Chen",
    title: "Smart Contract Auditor",
    hourlyRate: 120,
    rating: 4.9,
    completedJobs: 24,
    bio: "Security-focused smart contract auditor with a track record of identifying vulnerabilities in high-value protocols.",
    skills: ["Smart Contract Auditing", "Solidity", "Security", "DeFi", "Cryptography"],
    acceptedCryptocurrencies: ["ETH", "BTC", "USDT"],
    availability: "Project-based",
    location: "Remote",
    category: "development",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    title: "Content Writer",
    hourlyRate: 45,
    rating: 4.7,
    completedJobs: 52,
    bio: "Crypto-native content writer creating engaging content for blockchain projects and crypto platforms.",
    skills: ["Content Writing", "SEO", "Whitepapers", "Technical Writing", "Editing"],
    acceptedCryptocurrencies: ["BTC", "USDT", "BNB"],
    availability: "Freelance",
    location: "Remote",
    category: "writing",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
  },
  {
    id: "5",
    name: "David Kim",
    title: "Marketing Specialist",
    hourlyRate: 60,
    rating: 4.6,
    completedJobs: 38,
    bio: "Growth-focused marketing specialist for Web3 and crypto projects with experience in community building.",
    skills: ["Digital Marketing", "Community Management", "Social Media", "Growth Hacking", "Analytics"],
    acceptedCryptocurrencies: ["ETH", "BTC", "SOL"],
    availability: "Full-time",
    location: "Remote",
    category: "marketing",
    avatar: "https://images.unsplash.com/photo-1542178243-bc20204b769f?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
  },
  {
    id: "6",
    name: "Lisa Park",
    title: "Video Editor & Animator",
    hourlyRate: 55,
    rating: 4.7,
    completedJobs: 27,
    bio: "Creative video editor and animator specializing in cryptocurrency explainer videos and motion graphics.",
    skills: ["Video Editing", "Animation", "Motion Graphics", "After Effects", "Premiere Pro"],
    acceptedCryptocurrencies: ["BTC", "ETH", "BNB"],
    availability: "Project-based",
    location: "Remote",
    category: "audio",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
  },
];

// Mock data for jobs
export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Develop DeFi Yield Aggregator",
    company: "CryptoYield Finance",
    type: "full-time",
    duration: "3-6 months",
    budget: 8000,
    description: "We're looking for an experienced Solidity developer to build a new yield aggregator platform that automatically moves funds between different DeFi protocols for optimal returns.",
    skills: ["Solidity", "Smart Contracts", "DeFi", "Yield Farming", "Web3.js"],
    acceptedCryptocurrencies: ["ETH", "USDT", "BTC"],
    postedDate: "2 days ago",
    category: "development",
  },
  {
    id: "2",
    title: "Design NFT Marketplace UI/UX",
    company: "ArtBlock Labs",
    type: "part-time",
    duration: "1-2 months",
    budget: 4500,
    description: "Looking for a talented UI/UX designer to create a user-friendly interface for our upcoming NFT marketplace focused on digital art and collectibles.",
    skills: ["UI Design", "UX Design", "Figma", "NFT Knowledge", "Web3"],
    acceptedCryptocurrencies: ["ETH", "SOL"],
    postedDate: "1 week ago",
    category: "design",
  },
  {
    id: "3",
    title: "Write Technical Documentation for DEX",
    company: "SwapX Protocol",
    type: "one-time",
    duration: "2 weeks",
    budget: 1500,
    description: "We need comprehensive technical documentation for our decentralized exchange, including API references, integration guides, and developer resources.",
    skills: ["Technical Writing", "Documentation", "DEX Knowledge", "Markdown", "Clear Communication"],
    acceptedCryptocurrencies: ["BTC", "ETH", "USDT"],
    postedDate: "3 days ago",
    category: "writing",
  },
  {
    id: "4",
    title: "Community Manager for DAO",
    company: "GovernanceDAO",
    type: "full-time",
    duration: "Ongoing",
    budget: 3000,
    description: "Seeking an experienced community manager to grow and engage our DAO community across Discord, Telegram, and Twitter. Must understand governance mechanisms and tokenomics.",
    skills: ["Community Management", "Discord", "Telegram", "DAO Knowledge", "Tokenomics"],
    acceptedCryptocurrencies: ["ETH", "BTC"],
    postedDate: "5 days ago",
    category: "marketing",
  },
  {
    id: "5",
    title: "Create Explainer Videos for Crypto Platform",
    company: "CryptoLearn",
    type: "one-time",
    duration: "1 month",
    budget: 2500,
    description: "Looking for a video editor/animator to create 5 short explainer videos for our educational crypto platform, covering topics like DeFi, NFTs, and Layer 2 solutions.",
    skills: ["Video Editing", "Animation", "Motion Graphics", "Crypto Knowledge", "Storytelling"],
    acceptedCryptocurrencies: ["BTC", "USDT", "BNB"],
    postedDate: "1 week ago",
    category: "audio",
  },
];
