
import { TravelItem } from "@/types/travel";

// Mock data for hotels
export const mockHotels: TravelItem[] = [
  {
    id: "1",
    name: "Crypto Plaza Hotel",
    description: "Luxury hotel in the heart of the city with crypto payment options and exclusive NFT rewards for guests.",
    price: 250,
    originalPrice: 300,
    discountPercent: 16,
    rating: 4.8,
    reviewCount: 126,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "USDT"],
    location: "Dubai, UAE",
    region: "asia",
    features: ["Free WiFi", "Pool", "Crypto ATM", "Spa"],
    duration: "N/A",
  },
  {
    id: "2",
    name: "Blockchain Resort & Spa",
    description: "Beachfront resort with blockchain-themed amenities and direct crypto payment systems in all areas.",
    price: 380,
    originalPrice: 450,
    discountPercent: 15,
    rating: 4.9,
    reviewCount: 89,
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "SOL"],
    location: "El Salvador",
    region: "south-america",
    features: ["Beach Access", "Pool", "Restaurant", "Crypto-themed Events"],
    duration: "N/A",
  },
  {
    id: "3",
    name: "Digital Asset Suites",
    description: "Modern apartment hotel with smart home features controlled by blockchain technology.",
    price: 175,
    originalPrice: 0,
    discountPercent: 0,
    rating: 4.6,
    reviewCount: 74,
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "BNB"],
    location: "Singapore",
    region: "asia",
    features: ["Free WiFi", "Smart Home", "Workspace", "City View"],
    duration: "N/A",
  },
  {
    id: "4",
    name: "Token Lodge",
    description: "Boutique hotel with unique NFT art in each room and crypto enthusiast meetups.",
    price: 220,
    originalPrice: 0,
    discountPercent: 0,
    rating: 4.7,
    reviewCount: 53,
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "USDT"],
    location: "London, UK",
    region: "europe",
    features: ["Free WiFi", "Restaurant", "NFT Gallery", "Workspace"],
    duration: "N/A",
  },
];

// Mock data for flights
export const mockFlights: TravelItem[] = [
  {
    id: "1",
    name: "Crypto Air: New York to Tokyo",
    description: "Direct flight with special crypto holder benefits including lounge access and priority boarding.",
    price: 1200,
    originalPrice: 1500,
    discountPercent: 20,
    rating: 4.5,
    reviewCount: 89,
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "USDT"],
    location: "New York to Tokyo",
    region: "north-america",
    features: ["Direct", "WiFi", "Priority Boarding", "Crypto Payment Discount"],
    duration: "14h 20m",
  },
  {
    id: "2",
    name: "Blockchain Airways: London to Dubai",
    description: "Premium economy flight with special NFT rewards and in-flight crypto education content.",
    price: 850,
    originalPrice: 950,
    discountPercent: 10,
    rating: 4.3,
    reviewCount: 64,
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "BNB"],
    location: "London to Dubai",
    region: "europe",
    features: ["One Stop", "Premium Economy", "NFT Rewards", "WiFi"],
    duration: "7h 40m",
  },
  {
    id: "3",
    name: "Token Express: Singapore to Seoul",
    description: "Business class flight with exclusive crypto holder benefits and dedicated workspace.",
    price: 1100,
    originalPrice: 0,
    discountPercent: 0,
    rating: 4.7,
    reviewCount: 42,
    image: "https://images.unsplash.com/photo-1544016768-982d1554f0b9?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "SOL"],
    location: "Singapore to Seoul",
    region: "asia",
    features: ["Direct", "Business Class", "Lounge Access", "Crypto Payment"],
    duration: "6h 15m",
  },
  {
    id: "4",
    name: "DeFi Connect: San Francisco to El Salvador",
    description: "Special flight package for crypto entrepreneurs with networking opportunities onboard.",
    price: 780,
    originalPrice: 900,
    discountPercent: 13,
    rating: 4.4,
    reviewCount: 38,
    image: "https://images.unsplash.com/photo-1528214170403-b7a340248945?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "USDT"],
    location: "San Francisco to El Salvador",
    region: "north-america",
    features: ["One Stop", "WiFi", "Networking", "Bitcoin Payment"],
    duration: "8h 50m",
  },
];

// Mock data for experiences
export const mockExperiences: TravelItem[] = [
  {
    id: "1",
    name: "Crypto Mining Tour",
    description: "Visit a large-scale crypto mining operation and learn about the hardware and processes behind Bitcoin mining.",
    price: 120,
    originalPrice: 150,
    discountPercent: 20,
    rating: 4.8,
    reviewCount: 45,
    image: "https://images.unsplash.com/photo-1621501103258-d0984c76f851?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "USDT"],
    location: "Iceland",
    region: "europe",
    features: ["Guided Tour", "Equipment Demo", "Lunch", "Transportation"],
    duration: "5 hours",
  },
  {
    id: "2",
    name: "Blockchain Beach Retreat",
    description: "Week-long retreat for crypto enthusiasts with workshops, networking, and relaxation on pristine beaches.",
    price: 1800,
    originalPrice: 2200,
    discountPercent: 18,
    rating: 4.9,
    reviewCount: 28,
    image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "SOL"],
    location: "El Salvador",
    region: "south-america",
    features: ["Accommodation", "Workshops", "Beach Activities", "Networking"],
    duration: "7 days",
  },
  {
    id: "3",
    name: "NFT Gallery Tour",
    description: "Guided tour of exclusive NFT galleries and meetups with prominent artists in the space.",
    price: 85,
    originalPrice: 0,
    discountPercent: 0,
    rating: 4.7,
    reviewCount: 37,
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["ETH", "SOL", "BTC"],
    location: "Miami, USA",
    region: "north-america",
    features: ["Gallery Access", "Artist Meetups", "Digital Collectible", "Refreshments"],
    duration: "3 hours",
  },
  {
    id: "4",
    name: "Crypto Food Tour",
    description: "Explore restaurants and cafes that accept cryptocurrency payments with tastings at each location.",
    price: 65,
    originalPrice: 80,
    discountPercent: 18,
    rating: 4.6,
    reviewCount: 53,
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
    acceptedCryptocurrencies: ["BTC", "ETH", "USDT"],
    location: "Singapore",
    region: "asia",
    features: ["Food Tastings", "Drinks", "Walking Tour", "Local Guide"],
    duration: "4 hours",
  },
];
